### ISSUE TITLE
Generate JWS Message Signatures

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#299]
~As a platform user, I want to be able to test that my message signatures are well-formed. Note that since the ITP is intercepting and modifying messages, it may be necessary to regenerate the FSPIOP header for the SUT and simulators.~

- ~During session creation, the user should be able to select whether or not to check message signatures.~
- ~When signature checking is enabled, an additional test should be conducted verifying the presence and correctness of a JWS signature in the `FSPIOP-Signature` message header.~
- Keys/certificates for generating the signature can be found in the session environment.
- When signature checking is enabled, all outgoing messages should additionally be sent with a valid `FSPIOP-Signature` header. ~Where possible, this should be the original header from the sender, but if necessary~ the header can be reconstructed using keys in the session environment.

Message signature documentation: https://docs.mojaloop.io/mojaloop-specification/documents/Signature.html

**Comment by cjol** [comment]
@agalaguz @KolyaSirik I have been thinking about the UX of creating test cases which use JWS. I've described my proposed design below. If it's possible to integrate that into the ongoing work, that would be great, but otherwise we can use whatever you have already come up with, and maybe improve the UX in a future sprint.

Just like with [mTLS](https://github.com/gsmainclusivetechlab/interop-test-platform/issues/300) where we have added `mtls:true` to the `test_step`, we would also add an optional field `jws` to both `request` and `response` as follows:

```yaml
test_steps:
  - pattern: ^quotes/$
    # ... leave the other properties of the test_step intact
    mTLS: true
    request:      
      uri: /quotes
      method: POST
      # ... leave the other properties of the request intact
      jws:
        alg: RS256 # which algorithm to use for signing
        key: # ... some reference to the DFSP key to use for encryption
        protectedHeaders: # which of the message headers to include in the signature
          [FSPIOP-Destination, FSPIOP-URI, FSPIOP-HTTP-Method, Date, FSPIOP-Source]
        header: FSPIOP-Signature # Where to add the final signature
        transform: mojaloop # Transformations to apply to calculate the header
```

The parameters of `jws` are defined as follows:
### alg:
Fairly self-explanatory, just pass this value on to whatever JWS library we use. Normally we'll use RS256, I think.

### key:
I'm not sure how this will work with the new certificate management, but effectively this should be a reference to the certificate uploaded by a DFSP. For example, maybe it will be something like `"{{ env.CERTIFICATE_PATH }}"`.

### protectedHeaders:
These headers should be plucked from the request/response value and included in the signature. The JWS signature might be derived something like this (using the [`php-jws`](https://github.com/gamegos/php-jws) library as an example):
```php
$headers = array(
    'alg' => $step["jws"]["alg"],
    'FSPIOP-Destination': $step->headers["FSPIOP-Destination"],
    'FSPIOP-Source': $step->headers["FSPIOP-Source"],
    'FSPIOP-HTTP-Method': $step->headers["FSPIOP-HTTP-Method"],
    'FSPIOP-URI': $step->headers["FSPIOP-URI"],
    'Date': $step->headers["Date"],
);

$payload = $step->body;

$key = /* ... */;

$jws = new \Gamegos\JWS\JWS();
$signature =  $jws->encode($headers, $payload, $key);
```

### header:
This is the field where we will add the signature after it's calculated. For Mojaloop, the value will always be `FSPIOP-Signature`.

### transform:
In a normal environment, we would simply add the signature directly to the specified header. Mojaloop is a bit weird though - the value of the signature is supposed to be `Base64Url(JSON.stringify({ protectedHeaders, signature })`. To support both patterns, I have added this `transform` parameter. If the value === `"mojaloop"`, then the signature should be wrapped as I just described. In all other cases, the signature should be transmitted untransformed.

For a full example of the Mojaloop signing process, see [here](https://docs.mojaloop.io/mojaloop-specification/documents/Signature.html#41-generating-a-signature).
