### ISSUE TITLE
Remove Simulators

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#309]
This is a bit of a controversial suggestion, so I am creating an issue to track discussion. 

Currently, we have SUT components and simulator components. Both are external to the core platform. Messages from the simulators can be overridden using the `test_request_setups` field defined within a testcase. In extreme circumstances, the original message might not be used at all, with all fields being replaced in the proxy. If this is the case, why do we need the simulator at all?

Instead, my suggestion is that the test platform uses the `request` field to automatically generate a full request instead of making a callout to an external simulator. We actually already do this in a limited way - when a test case starts with a request from a simulator, the ITP constructs a fake request to initiate the flow when the user clicks the "Execute Test Case" button.

**Comment by brunosmm** [comment]
Some food for thought:

- What happens if the message does not match with any test case? Today the simulator will still respond with a "correct" message flow.
- Current you send the message to a session URL and at the end add the correct endpoint of the API your testing, like /transaction, /quotes, etc. who create those endpoints today? the platform(proxy) or the simulators? Going to s "_simulatorless_" way how you add the possible endpoints needed?

**Comment by cjol** [comment]
1. If an incoming message today doesn't match any test cases, it will not be forwarded to the simulator, so the simulator will not respond with the "correct" message. So it would be the same if we drop the simulators. If an incoming message doesn't match any test cases, the platform will not generate a response.
2. The endpoints will be read from the test cases, the same way they currently are. The platform sees an incoming message, and extracts the end of the URL. If it finds a test case that matches this url segment, it will generate a response based on the test case definition. It will then move on to the next test step and generate a request according to the `request` defined there. If the next request is heading for another simulator, this request will be a "self-request" from the ITP and straight back to the ITP (clearly we could optimise this and avoid actually making the request). When this request is received, we repeat the above.

A bigger question is about "logic". If I sent a request with `payload: 10`, then subsequent requests might need to use the same payload. In which case, we would need to add a way to map values from one request into later ones. 

However there's a question mark in my mind over whether this logic is required at all. If the SUT behaves correctly (according to the "script" defined in the test case), then do we need to read any "variable" data? Or is it sufficient to hard-code the value (10 in the example above) into all steps of the test case script?

**Comment by cjol** [comment]
We could support quite advanced logic, as well as substitution and other things by treating the `request` and `response` fields inside a test case definition as [twig](https://twig.symfony.com/) templates. Twig comes with a security sandbox, which allows us to safely evaluate the template even though it is potentially coming from an untrusted source.

**Comment by cjol** [comment]
I've been preparing some slides to explain this behaviour, and I thought I would include the important bits here as well.

Here's an overview of the flow without simulators (not too different from the current flow):
![Screenshot 2020-11-19 at 15 09 27](https://user-images.githubusercontent.com/1517675/99684598-896d8e80-2a79-11eb-9078-fa4a54b8cff1.png)

Here is additionally a mockup of what a request template might look like using twig templating:

```yaml
test_steps:
  - # test_step[0]
  - # ...
  - # test_step[n]
    # ... other fields
    request_template:
      source: Mojaloop
      target: DFSP1
      method: PUT
      path: '/quotes/{{ test_steps[2].path_parameters.ID }}'
      headers:
        Content-Type: application/json
        Accept: application/vnd.interoperability.quotes+json;version=1.0
        Date: '{{ "now" | date("D, d M Y H:i:s O") }}'
        FSPIOP-Source: '{{ environment.DFSP2_ID }}'
        FSPIOP-Destionation: '{{ environment.DFSP1_ID }}'
      body: |
        {
            "transferAmount":{
                "amount":"99",
                "currency": "{{ test_steps[0].request.body.amount.currency }}"
            },
            "payeeFspCommission":{
                "amount":"1",
                "currency": "{{ test_steps[0].request.body.amount.currency }}"
            },
            "payeeReceiveAmount":{
                "amount":"100",
                "currency": "{{ test_steps[0].request.body.amount.currency }}"
            }
        }
    response_template: # ...
```
