### ISSUE TITLE
Test Case Editor Breaks Variables

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#360]
When editing a test case through the editor, variables in the path of a test step somehow break (it's possible that this also happens in other places). My current guess is that it's due to URL encoding values or something, but I haven't done a deep investigation yet. 

## Steps to reproduce

1. Create a new testcase using the template like the below (note that there are non-standard components here, but they can probably be replaced):
```
name: Mowali Setup Callbacks
slug: mowali-setup-callbacks
use_case: Test
behavior: positive
description: |
  Allows MPOP to set up callback URLs instructing Mowali to send callbacks to MPOP.
precondition: |
  - DFSP 1 and DFSP 2 exist in Mojaloop as Participants.
  - The following values are set in the session environment:
    - SUT_OAUTH_TOKEN
    - SUT_FSPIOP
    - REMOTE_FSPIOP
    - REMOTE_OAUTH_TOKEN
components:
  - Mowali Onboarding Platform
  - Mowali Central Admin
test_steps:
  - path: participants/{FSPIOP}/endpoints
    pattern: 'participants/[^/]+/endpoints$'
    method: POST
    source: Mowali Onboarding Platform
    target: Mowali Central Admin
    api_spec: Mojaloop v1.0
    test_response_scripts:
      - name: Transaction was successfully accepted
        rules:
          status: 'required|in:201'
    request:
      method: POST
      uri: participants/${SUT_FSPIOP}/endpoints
      # uri: /parties/MSISDN/${REMOTE_PARTY_MSISDN}
      headers:
        Accept: 'application/json'
        Content-Type: 'application/json'
        Date: '${CURRENT_TIMESTAMP_RFC2822}'
        Authorization: Bearer ${SUT_OAUTH_TOKEN}
      body:
        type: 'FSPIOP_CALLBACK_URL_QUOTES'
        value: ${MMO1_BASE_URI}
    response:
      status: 201
      headers:
        content-type: 'application/json'
      body:
```
2. Create a new session with `Mowali Central Admin` as SUT, containing the new test case and a value for the variable `SUT_FSPIOP`.
3. Execute the test case, and note that the variable is correctly substituted
4. Edit the test step in the visual editor, then save and publish the test case
5. Update the test case in the session, and rerun the test
6. Note that the variable is not substituted.

![image](https://user-images.githubusercontent.com/1517675/102620763-701e3780-4136-11eb-9bdb-67c141ec2fe2.png)
