### ISSUE TITLE
Verify ILP Packet

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#391]
Now that the simulators support generation of ILP packets, we can conduct a full test using ILP. 

Unfortunately, if a SUT malforms an ILP packet, the ITP is currently unable to identify the problem and highlight it as a failed test. I don't know whether it will be easier to add this as a custom Laravel validation rule or some other way, but I imagine it will fit into the `test_request_script` section somehow.

We can test the packet by deconstructing it using the reverse logic from the simulator. This allows us to check that the individual values within the ILP packet are correctly constructed. For example, we may not know what the correct value for "condition" is at the time that a test is performed, but we should nonetheless check that the `amount` field is correctly specified.

**Comment by agalaguz** [comment]
Hey Christopher, @cjol 
Just wanted to fully understand 

> Now that the simulators support generation of ILP packets/JWS signature

Is it https://github.com/mojaloop/simulator that includes both features from #391 and #392 so we can re-use those algorithms? 
Could you please advise? Thank you!

**Comment by cjol** [comment]
Hi Anton, I meant to include a link and I forgot! We already implemented construction of ILP packet in this (unmerged) file: https://github.com/gsmainclusivetechlab/interop-test-platform/blob/feature/gsma-changes/src/app/Extensions/Twig/IlpPacket.php

These algorithms might need to be "reversed" to support validation, but hopefully this gives a helpful starting point!

**Comment by agalaguz** [comment]
Hi Christopher @cjol,  
We've written a validation function that can be added to `test_request_script` and that will check if `amount` in `body` and `amount` encoded in `ilpPacket` are equal, e.g. both are `5`. 
The syntax on UI is like this:  
![image](https://user-images.githubusercontent.com/16337770/107537899-14b77580-6bcc-11eb-9b0b-9994fa1e5550.png)

Will `amount` validation be enough? or some other values from `body` should be checked against ones encoded in `ilpPacket`?
Thank you.

**Comment by cjol** [comment]
If it's possible, it would also be useful to check `condition` and `address`.

Looking at the syntax, I'm not sure exactly how it works. Would I be able to do `required|ilpPacket:5` or is it exclusively used to read from other body fields? The reason being able to do `ilpPacket:5` is useful is in case I want to reference other steps using twig - `ilpPacket:{{ steps.1.request.body.amount.amount}}` for example.

**Comment by agalaguz** [comment]
@cjol,  thank you for your comments.
From what we see from `ilpPacket()` code generator -> it may use up to **5 variables** to generate `ilpPacket`. 
They are:
- `$amount`, 
- `$expires`, 
- `$condition`, 
- `$destination`, 
- `$data`

`$amount`, `$expires`, and `$condition` are clear for us: http://prntscr.com/z42i75 

`$destination` is a `fspiop-destination` header that was also noted as `address` in your previous message?  

BTW, we expect ilpPacket validation to work this way: 
1. Once the message is received `ilpPacket` test script checks if all data coded inside `ilpPacket` equals the related data in message. e.g. `$amount` is 5 in `ilpPacket` and in `body.amount`. And shows Pass/Fail result.

Please let us know if this makes sense?

**Comment by cjol** [comment]
`$destination` represents the destination party in the ILP protocol, so it's related to the party identifier rather than the FSPIOP header. Here is how I currently construct ILP packets using Twig:
```yaml
        ilpPacket: '{{ilpPacket(
          steps.6.request.body.amount.amount,
          "now",
          ilpCondition(ilpFulfilment()),
          "",
          "") | base64_urlencode}}'
```
 
$destination and $data (empty in the example above) do not exist elsewhere inside the message, so we can't do a check from "`lpPacket->$destination`" against "`body->$destination`" the way you describe it. Instead I was hoping we could insert a custom value into the rule (e.g. from the environment). The same way that we can do rules like this currently (see we are checking that the SUT has provided the correct MSISDN by reading a variable from the environment):

![image](https://user-images.githubusercontent.com/1517675/107668495-a7b5e580-6c88-11eb-8a40-09e94bad8013.png)

I basically want to check that the SUT has constructed the ilp packet in the same way that the simulator did it, so I would expect the final rules to be something like this:
```yaml
        rules:
          body.ilpPacket: 
             - 'required'
             - 'regex:/^[A-Za-z0-9-_]+[=]{0,2}$/'
             - 'ilpPacketAmount:{{ env.TRANSFER_AMOUNT }}'
             - 'ilpPacketDestination:g.gh.msisdn.{{steps.6.request.body.payee.partyIdInfo.partyIdentifier}}' # this might refer to a previous step
             - 'ilpPacketCondition:{{steps.7.request.body.condition}}'  # this would need to refer to the current step
```

I don't really mind how the syntax works - it can be different to my suggestion but hopefully it gives you an idea of what I am trying to validate. It might be even better if we could somehow "extract" all the values to the top level so that we can use all laravel validators:

```yaml
        rules:
          body.ilpPacket: 'required|regex:/^[A-Za-z0-9-_]+[=]{0,2}$/'
          body.ilpPacket.amount: 'min:100' # we can use any Laravel validations here now
          body.ilpPacket.condition: 'in:{{ steps.7.request.body.condition }}'
          body.ilpPacket.destination: 'regex:/{{ steps.6.request.body.payee.partyIdInfo.partyIdentifier }}$/'
```

But in that case I can't think of a way to tell ITP that it needs to "extract" `body.ilpPacket` - so this might not be possible but I am mentioning it in case you have an idea!
