### ISSUE TITLE
Incorrect "Secure" URL Generated

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#400]
0. Create a new component called "mTLS server"
1. Create a simple mTLS test case:
```yaml
name: "SSL Demo"
use_case: Test
slug: mtls-demo
behavior: positive
components: 
  - "Service Provider"
  - "mTLS Server"
test_steps: 
  - source: "Service Provider"
    target: "mTLS Server"
    method: GET
    mtls: true
    path: /test
    pattern: test
    request: 
      body: empty_body
      method: GET
      uri: test
    response: 
      body: empty_body
      status: "200"
```
2. Enable encryption to tls server: 
![image](https://user-images.githubusercontent.com/1517675/105477367-aa30ab00-5c99-11eb-8e63-a3ace9f9121c.png)
3. Copy URL for Service Provider to talk to mTLS server:
![image](https://user-images.githubusercontent.com/1517675/105477660-101d3280-5c9a-11eb-9375-900b4facbff0.png)

Expected result:
```
https://mojaloop.dev.interop.gsmainclusivetechlab.io/testing/.../.../.../sut
```

Actual result:
```
https://mojaloop.dev.interop.gsmainclusivetechlab.io/testing-insecure/.../.../.../sut
```

Note also that if I access the session via an HTTP connection, the following result is given which is even more wrong (the component URL should be HTTPs even if the session was viewed over an http connection):
```
http://mojaloop.dev.interop.gsmainclusivetechlab.io/testing-insecure/.../.../.../sut
```
