### ISSUE TITLE
Add "Exact Match" validator

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#408]
Now that we have more powerful test case syntax, we can have more powerful tests. For example, where previously we would only be able to check that an ilpPacket has the correct regex format, we can now check that it is _exactly_ the correct value by referring to an earlier step. For example, we can have the following test:

```yaml
      - name: ILP is correctly forwarded
        rules:
          body.expiration: 'required|in:{{steps.8.request.body.expiration}}'
          body.ilpPacket: 'required|in:{{steps.8.request.body.ilpPacket}}'
          body.condition: 'required|in:{{steps.8.request.body.condition}}'
```

Unfortunately, the `in` validator is not ideal. For starters, it's not very descriptive, so it would be good to add a validator called "str_equals" to make it clear that there is only one correct value. Secondly, if the data in question contains special characters (e.g. pipe marks `|` or spaces ` `) we will run into problem where laravel incorrectly parses the expected value.

I would like the new "str_equals" validator to look something like this in use:
```yaml
      - name: ILP is correctly forwarded
        rules:
          body.ilpPacket: 
             - 'required'
             - str_equals:
                 - '{{steps.8.request.body.expiration}}'
```

By splitting the expected value into an array instead of encoding it inside a single string, we don't have to worry about special characters giving wrong results.

Note that existing validators' syntax should be unchanged.
