### ISSUE TITLE
Consolidate Assertions under test_*_scripts

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#486]
Right now we have multiple types of assertion:

- api spec assertions (in `step.api_spec`)
- laravel validation assertions (in `step.test_request_scripts` or `step.test_response_scripts`)
- mtls assertions (enabled by `step.mtls: true`)
- jws assertions (enabled by `step.request.jws: *` and `step.response.jws: *\)

In the future, we may have other types of assertions which can't be encoded by a laravel validation, and we would have to add them to the "step" namespace. I'd like to consolidate all of these into a single "assertions" field, which clarifies the purpose of the field while also giving a flexible container for new types of assertion. The mental model for an assertion should be "a test which is applied to the message without blocking execution of the test".

To do this, I would propose the following changes to the step schema:

```yaml
  - path: # unchanged
    pattern: # unchanged
    method: # unchanged
    source:  # unchanged
    target:  # unchanged
    request: 
       simulate:  
           # ... current contents of the step.requests
           jws_sign: 
             alg: RS256 
             private_key: '{{ env.DFSP1_JWS_PRIVATE_KEY }}'
             header: 'FSPIOP-Signature'
             protectedHeaders: [...] # unchanged
             transform: mojaloop
       assertions:
          api_spec: 'Mojaloop v1.0'
          mtls: true
          jws_verify: 
             alg: RS256 
             public_key: '{{ env.DFSP1_JWS_PUBLIC_KEY }}'
          json_validations: # current contents of step.test_request_scripts
    response: 
       simulate:  
           # ... current contents of the step.response
           jws_sign: 
             alg: RS256 
             private_key: '{{ env.DFSP1_JWS_PRIVATE_KEY }}'
             header: 'FSPIOP-Signature'
             protectedHeaders: [...] # unchanged
             transform: mojaloop
       assertions:
          api_spec: 'Mojaloop v1.0'
          mtls: true
          jws_verify: 
             alg: RS256 
             public_key: '{{ env.DFSP1_JWS_PUBLIC_KEY }}'
          json_validations: # current contents of step.test_response_scripts
```

Some slight subleties in the above:

 - `api_spec` is now specified separately in request and response. This allows us to, for example, test a component's response to an invalid request payload by including `api_spec` on the response but not on the request (cc @brunosmm).
 - `mtls` is now specified separately in request and response. This is a more accurate model for the current connection config options, where there are two separate mtls connections being brokered by the ITP proxy. Currently if the destination component is using an unencrypted connection, the mtls assertion will still pass. (in practice, this should only occur during testing, since in normal conditions there would only be one connection, so both ITP connections should be encrypted or neither of them should be). 
 - `jws_verify` has been separated from `jws_sign` (currently both are controlled by the same `jws` block on the step). This makes it clearer that the private key is not required if the JWS is generated by a SUT - and allows us to generate a JWS without necessarily validating it.
 - The laravel validations have been explicitly named `json_validations` since they operate on a JSON-like object. The name allows us to use different validation options for alternative datatypes like XML in future.

This results in a small amount of repetition (`api_spec`, `mtls` and `jws_verify.alg` need to be repeated in two places instead of one), but it gives the test case creator a better mental model for what is happening, and gives the test case author more control over the "Automatic" assertions that we currently have. The repetition can probably also be avoided using YAML aliases.
