### ISSUE TITLE
Discussion: "Decoders" for laravel validations

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#488]
Laravel validators offer a flexible syntax for simple data structures. However, APIs often use encoded data which is currenly difficult to validate. For example:
 - The ILP data packet in the Mojaloop FSPIOP API
 - A JSON-encoded string inside a header
 - A base64-encoded JWT token

It would be useful to have a way to express a "decode" operation which would be applied to a field before it is passed to the laravel validation. Here are some syntax ideas for discussion:

### New object schema for rules

```yaml
test_request_scripts:
      - name: ILP packet contains valid data
        rules:
          body.ilpPacket:
             decoder: ILP
             rules:
                amount: 'required|gt:0'
                data:
                   decoder: JSON
                   rules:
                      transactionId: 'required|in:{{steps.5.request.body.transactionId}}'
```

However, I think this would be incompatible with the current syntax for laravel rules, and since this is an advanced usecase I don't want to complicate the current syntax for more common validations.

### Custom syntax in object keys
```yaml
test_request_scripts:
      - name: ILP packet contains valid data
        rules:
          '(body.ilpPacket | decodeILP).amount': 'required|gt:0'
          '((body.ilpPacket | decodeILP).data | decodeJSON).transactionId': 'required|in:{{steps.5.request.body.transactionId}}'
```

The main problem here is that we need to parsing the custom syntax for decoders, which is likely to make things harder for ourselves than necessary.

### Twig syntax in object keys
Maybe we can do something clever with twig syntax to avoid parsing the string keys ourselves?

```yaml
test_request_scripts:
      - name: ILP packet contains valid data
        rules:
          '{{ (body.ilpPacket | decodeILP).amount }}': 'required|gt:0'
          '{{ ((body.ilpPacket | decodeILP).data | decodeJSON).transactionId }}': 'required|in:{{steps.5.request.body.transactionId}}'
```

We have slightly simplified the implementation compared to the previous option, but it's still not a complete solution because now we're asking Laravel to parse a rule that looks like this (which I don't think it will!):
```yaml
'100': 'required|gt:0'
'abcd-1231-123132-1213': 'required|in:abcd-1231-123132-1213'
```

Please share any other syntax ideas below, or offer feedback on these ones! @brunosmm @eudisley @SamyBouch
