### ISSUE TITLE
"Saved Data" for test steps

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#489]
Occasionally, it's useful to use Twig to do computations to derive some data. If the output of this data is not placed inside the body or header, it can be difficult to retrieve in a future step. 

As an example, if a simulator needs to send a message to a URL of the form `/transactions/{{ uuid() }}`. If I want to retrieve the UUID in a future step, it's difficult. We could possibly extract it using regex from `steps.X.request.uri` but that doesn't solve all situations.

For another example, the ILP packet in the Mojaloop FSPIOP API is derived from a "secret", which is generated freshly for the request but which is not sent. In a future step, the secret is shared - and at this stage we would want to validate that the shared secret is the same as the one from earlier - but currently we cannot.

As a solution to both situations, I suggest creating a "data" field inside test_step. This should be a yaml object, which is templatable using twig like `request` and `response` currently are. The template should be evaluated before any other templates in the step, and it should be accessible as `steps.X.data` inside the other templates for the current step. For example:

```yaml

test_steps:
  - path: /transactions/{Id}
    data:
       txnId: '{{ uuidv4() }}'
    request:
       method: POST
       uri: 'transactions/{{ steps.1.data.txnId }}'
  # ...
  - path: /later-step
    test_request_scripts:
       - name: Transaction ID is correctly specified
         rules:
           body.transactionId: 'required|in:{{ steps.1.data.txnId }}'
```

For the ILP example, we can do this:
```yaml
      data: |
        {% set expiry = date("+1 hour") | date("Y-m-d\\TH:i:s.vP") %}
        {% set secret = ilpSecret() %}
        {% set condition = ilpCondition(secret) %}
        {% set data = "" %}
        {% set ilpPacket = ilpPacket(
              steps.6.request.body.amount.amount,
              expiry,
              condition,
              "g.gh.msisdn.#{steps.6.request.body.payee.partyIdInfo.partyIdentifier}",
              data
            ) %}
        {{
          {
            secret: secret,
            expiration: expiry ,
            condition: condition ,
            ilpPacket: ilpPacket
          } | json_encode
        }}
     request:
        transferAmount:
           currency: 'GBP'
           amount: '100'
        ilpPacket: '{{ steps.1.data.ilpPacket }}'
        expiration: '{{ steps.1.data.expiration }}'
        condition: '{{ steps.1.data.condition }}'
```

Now future steps can access `steps.1.data.secret` to verify the packet is correct.
