### ISSUE TITLE
Add "currentStep" to twig environment 

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#491]
I would like a new variable to be added to the twig environment called "currentStep". It should be equal to the number of the current step. This will allow us to have relative step indexes to e.g. refer to "the step before the current one:"

```yaml
request:
   body:
       transactionId: '{{ steps[currentStep - 1].request.body.transactionId }}'
```
