### ISSUE TITLE
Allow Patching Requests

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#528]
Some users of the platform may need to modify requests made by the simulator before they are made. For example, they may wish to add an `Authorization` header, which is not defined inside the test case. 

Currently, this is possible in a limited way, if the test case author adds logic to the test case to handle this customisation. As a generic alternative, we could allow arbitrary "patches" to be applied to a request/response based on a JSON file uploaded to the session environment. This would be based on the [JSON patch](http://jsonpatch.com/) standard. As an example, a test case could be defined like this:

```yaml
slug: 'my_test_case'
patches: '{{ file_env.TEST_CASE_PATCHES }}'
test_steps:
  - request: 
      method: POST
      uri: /biscuits
      headers:
        Accept: 'application/json'
        Content-Type: 'application/json'
      body: 
        biscuits:
           - { name: Digestive }
           - { name: Choco Leibniz }
```

When creating a session, a user would then be able to upload a JSON/YAML file to the variable `TEST_CASE_PATCHES` as follows (the file could also be added to the group's environment to simplify session creation):

```yaml
my_test_case: # keys in this object correspond to test case slugs
  test_steps:
    - request: 
      headers:
        - { op: remove, path: '/Accept' }
        - { op: add, path: '/Authorization', value: 'my-super-secret-auth-token' }
      body:
        - { op: replace, path: '/biscuits/1/name', value: Hobnob }
        - { op: add, path: '/biscuits/-', value: { name: 'Party Rings' } }
```

For each step, the test case engine willl check whether any patches have been defined for the request body or header, or the response body or header. When the test case is executed, the fields are generated as normal, and then the JSON patch is applied afterwards, to result in the following example request being sent

```
POST /biscuits
Content-Type: application/json
Authorization: my-super-secret-auth-token

{ "biscuits": [ {"name": "Hobnob"}, {"name": "Choco Leibniz"}, {"name": "Party Rings"} ] }
```

Note that this approach does allow the session owner to change anything about the requests being made by the simulator - which is a powerful tool, but may also lead to a test case execution deviating from the intended specification. When this happens, however, the test case assertions should nonetheless indicate that the request is malformed, and display a failure.
