### ISSUE TITLE
Test Case Headers cannot be manipulated as Twig objects

### ISSUE THREAD

**Issue by cjol** [gsmainclusivetechlab/interop-test-platform#530]
We have a need to allow clients to add custom headers based on environment variables. In the following test case, I would expect each of the following to work, but in fact only step 1 functions correctly:

```yaml
name: Custom header example
slug: custom-header-example
use_case: Demo
behavior: positive
description: |
  This test case demonstrates the ability to set custom headers in the session environment
precondition: ''
components:
  - name: Client
    slug: client
  - name: Server
    slug: server
test_steps:
  # WORKS
  - source: client
    target: server
    path: /demo
    pattern: '.*'
    method: GET
    test_request_scripts: []
    test_response_scripts: []
    request:
      method: GET
      uri: /demo
      headers:
        date: '{{"now" | date("D, d M Y H:i:s T", "GMT")}}'
        x-custom-value: '{{env.X_CUSTOM_VALUE}}'
    response:
      status: 202

  # WORKS ONLY IF X_CUSTOM_KEY is defined
  - source: client
    target: server
    path: /demo
    pattern: '.*'
    method: GET
    test_request_scripts: []
    test_response_scripts: []
    request:
      method: GET
      uri: /demo
      headers:
        date: '{{"now" | date("D, d M Y H:i:s T", "GMT")}}'
        x-custom-value: '{{env.X_CUSTOM_VALUE}}'
        '{{ env.X_CUSTOM_KEY }}': '{{env.X_CUSTOM_VALUE}}'
    response:
      status: 202

  # DOES NOT WORK (optional headers with twig example)
  # Expected result: https://twigfiddle.com/m4xk03
  - source: client
    target: server
    path: /demo
    pattern: '.*'
    method: GET
    test_request_scripts: []
    test_response_scripts: []
    request:
      method: GET
      uri: /demo
      headers: |
        {%
          set headers = {
            date: "now" | date("D, d M Y H:i:s T", "GMT"), 
            'x-custom-value': env.X_CUSTOM_VALUE
          }
        %}
        {% if env.X_CUSTOM_KEY is defined %}
        {%   set headers = headers | merge({(env.X_CUSTOM_KEY): env.X_CUSTOM_VALUE}) %}
        {% endif %}
        {{
          headers | json_encode(constant('JSON_PRETTY_PRINT'))
        }}
    response:
      status: 202

  # DOES NOT WORK (multiple headers example using json_decode)
  # Expected result: https://twigfiddle.com/sd9sd2
  - source: client
    target: server
    path: /demo
    pattern: '.*'
    method: GET
    test_request_scripts: []
    test_response_scripts: []
    request:
      method: GET
      uri: /demo
      headers: |
        {#
          We would also need do add a custom "json_decode" filter for this to work
        #}
        {% set patch = env.X_CUSTOM_HEADERS | json_decode %}
        {{
          {
            date: "now" | date("D, d M Y H:i:s T", "GMT"),
          } 
          | merge(patch)
          | json_encode(constant('JSON_PRETTY_PRINT'))
        }}
    response:
      status: 202

  # DOES NOT WORK (simple twig example)
  # Expected result: https://twigfiddle.com/vez6h9
  - source: client
    target: server
    path: /demo
    pattern: '.*'
    method: GET
    test_request_scripts: []
    test_response_scripts: []
    request:
      method: GET
      uri: /demo
      headers: |
        {{
          {
            date: "now" | date("D, d M Y H:i:s T", "GMT"), 
            x-custom-value: env.X_CUSTOM_VALUE
          } | json_encode
        }}
    response:
      status: 202

  # DOES NOT WORK (simple example without twig)
  - source: client
    target: server
    path: /demo
    pattern: '.*'
    method: GET
    test_request_scripts: []
    test_response_scripts: []
    request:
      method: GET
      uri: /demo
      headers: |
        {
          "date": "now",
          "x-custom-value": "env.X_CUSTOM_VALUE"
        }
    response:
      status: 202
```

The problem seems to be that the request headers are retrieved from the database as an object, instead of being allowed to be a string (like the request body). When we pass a string containing a twig template, this seems to get resolved as an empty set of headers (`{}`), and so the twig template is lost.
