### ISSUE TITLE
Admin Test Case Page - Error 500

### ISSUE THREAD

**Issue by SamyBouch** [gsmainclusivetechlab/interop-test-platform#546]
https://compliance.mobilemoneyapi.io/admin/test-cases

## Steps to reproduce

_Currently only present on compliance platform_

1. Navigate to admin/test-cases 
2. See 500 Error

## Additional info

Seems this error has come out of nowhere so I'm not sure what has caused it. One thing I can add is I tried manually editing a test case within the platform by navigating to the url directly (i.e https://compliance.mobilemoneyapi.io/admin/test-cases/589/test-steps) and once finished making changes the url now displays a 500 error as well. 

Laravel.log
`[2021-07-30 14:29:02] production.ERROR: Argument 1 passed to GuzzleHttp\Psr7\Response::__construct() must be of the type int, string given, called in /var/www/html/app/Casts/ResponseCast.php on line 33 {"userId":3,"exception":"[object] (TypeError(code: 0): Argument 1 passed to GuzzleHttp\\Psr7\\Response::__construct() must be of the type int, string given, called in /var/www/html/app/Casts/ResponseCast.php on line 33 at /var/www/html/vendor/guzzlehttp/psr7/src/Response.php:94)`

**Comment by SamyBouch** [comment]
The issue was caused by some test cases which had a `jws` parameter before the body like so:

```
      jws:
        alg: RS256
        key: '{{ file_env.CERTIFICATE_PATH }}'
        public_key: '{{ file_env.PUBLIC_CERTIFICATE_PATH }}'
        protectedHeaders:
          - x-callback-url
          - x-date
        header: FSPIOP-Signature
      headers:
        accept: 'application/json'
        content-type: 'application/json'
        x-callback-url: '{{ env.SP_BASE_URI }}/callback'
        x-date: '{{ new_date_iso8601() }}'
```
which caused the error shown in the post above. Once the test cases were updated without the `jws` field, the 500 errors disappeared.
